"""SDK для агентов платформы AI-агентов кафедры МИРЭА."""
from portal_sdk.manifest import (
    CategoryStrict,
    CheckboxField,
    DateField,
    DockerConfig,
    FileType,
    FolderFile,
    InputType,
    LimitsConfig,
    LLMConfig,
    Manifest,
    MultiFilesField,
    NumberField,
    OutputField,
    OutputType,
    RadioField,
    RuntimeConfig,
    SelectField,
    SelectOption,
    SingleFileField,
    TextareaField,
    TextField,
    ZipFile,
)

__version__ = "0.1.0"

__all__ = [
    "CategoryStrict",
    "CheckboxField",
    "DateField",
    "DockerConfig",
    "FileType",
    "FolderFile",
    "InputType",
    "LLMConfig",
    "LimitsConfig",
    "Manifest",
    "MultiFilesField",
    "NumberField",
    "OutputField",
    "OutputType",
    "RadioField",
    "RuntimeConfig",
    "SelectField",
    "SelectOption",
    "SingleFileField",
    "TextField",
    "TextareaField",
    "ZipFile",
    "__version__",
]
